### ISSUE TITLE
Code review needed

### ISSUE THREAD

**Issue by chaputan** [PolytechLyon/isi3-singleton-chaput-cottet-singleton#1]
Bonjour,

Pourriez-vous nous donner votre avis sur le TP et le rapport ?
Nous avons pas encore à l'état actuel faire fonctionner le programme sur Spring Boot.

Cordialement

**Comment by Slashgear** [comment]
- [ ] Il manque la définition du contexte spring. Je suis sur que vous pouvez me trouver un truc sur internet et me l'expliquer  😉 

- [ ] La définition de l'autowiring est approximative

- Votre configuration springboot est un peu capillo-tractée mais ça fait le café. J'aurais aussi pu vous conseiller de passer par des spring profil.
Voici un article https://jeanchristophegay.com/spring-et-les-profils/

Mais laisser ça dans l'état ce que vous avez fait me suffit.

**Comment by chaputan** [comment]
Merci pour le retour, le rapport a été modifié afin d'essayer de répondre aux derniers points ouverts.
